In [1]:
from einops import rearrange
import torch
ims = torch.tensor([
    [[[ 1], [ 2]], [[ 3], [ 4]]],  # Batch 0
    [[[ 5], [ 6]], [[ 7], [ 8]]],  # Batch 1
    [[[ 9], [10]], [[11], [12]]],  # Batch 2
    [[[13], [14]], [[15], [16]]],  # Batch 3
    [[[17], [18]], [[19], [20]]],  # Batch 4
    [[[21], [22]], [[23], [24]]],  # Batch 5
])

In [2]:
rearrange(ims, "b h w c -> (b h) w c") #(bh)这一维是b1_h1,b1_h2,b2_h1,b2_h2,b3_h1,b3_h2...,下同理

tensor([[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]],

        [[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]],

        [[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [18]],

        [[19],
         [20]],

        [[21],
         [22]],

        [[23],
         [24]]])

In [3]:
rearrange(ims, "b h w c -> (h b) w c")

tensor([[[ 1],
         [ 2]],

        [[ 5],
         [ 6]],

        [[ 9],
         [10]],

        [[13],
         [14]],

        [[17],
         [18]],

        [[21],
         [22]],

        [[ 3],
         [ 4]],

        [[ 7],
         [ 8]],

        [[11],
         [12]],

        [[15],
         [16]],

        [[19],
         [20]],

        [[23],
         [24]]])

In [4]:
rearrange(ims, "b h w c -> h (b w) c")

tensor([[[ 1],
         [ 2],
         [ 5],
         [ 6],
         [ 9],
         [10],
         [13],
         [14],
         [17],
         [18],
         [21],
         [22]],

        [[ 3],
         [ 4],
         [ 7],
         [ 8],
         [11],
         [12],
         [15],
         [16],
         [19],
         [20],
         [23],
         [24]]])

In [5]:
rearrange(ims, "(b1 b2) h w c -> b1 b2 h w c ", b1=2)

tensor([[[[[ 1],
           [ 2]],

          [[ 3],
           [ 4]]],


         [[[ 5],
           [ 6]],

          [[ 7],
           [ 8]]],


         [[[ 9],
           [10]],

          [[11],
           [12]]]],



        [[[[13],
           [14]],

          [[15],
           [16]]],


         [[[17],
           [18]],

          [[19],
           [20]]],


         [[[21],
           [22]],

          [[23],
           [24]]]]])

In [6]:
rearrange(ims, "(b1 b2) h w c -> (b1 h) (b2 w) c ", b1=2) #上一个(b1,b2,h,w,c)张量的b11_h1有三个

tensor([[[ 1],
         [ 2],
         [ 5],
         [ 6],
         [ 9],
         [10]],

        [[ 3],
         [ 4],
         [ 7],
         [ 8],
         [11],
         [12]],

        [[13],
         [14],
         [17],
         [18],
         [21],
         [22]],

        [[15],
         [16],
         [19],
         [20],
         [23],
         [24]]])

In [7]:
rearrange(ims, "(b1 b2) h w c -> (b2 h) (b1 w) c ", b1=2)

tensor([[[ 1],
         [ 2],
         [13],
         [14]],

        [[ 3],
         [ 4],
         [15],
         [16]],

        [[ 5],
         [ 6],
         [17],
         [18]],

        [[ 7],
         [ 8],
         [19],
         [20]],

        [[ 9],
         [10],
         [21],
         [22]],

        [[11],
         [12],
         [23],
         [24]]])

In [8]:
rearrange(ims, "(b1 b2) h w c -> h (b1 b2 w) c ", b1=2) #为rearrange(ims, "b h w c -> h (b w) c")，(b1 b2 w)这一维，并不是从b11_b21_w1(1和3吧)开始

tensor([[[ 1],
         [ 2],
         [ 5],
         [ 6],
         [ 9],
         [10],
         [13],
         [14],
         [17],
         [18],
         [21],
         [22]],

        [[ 3],
         [ 4],
         [ 7],
         [ 8],
         [11],
         [12],
         [15],
         [16],
         [19],
         [20],
         [23],
         [24]]])

In [9]:
rearrange(ims, "(b1 b2) h w c -> h (b2 b1 w) c ", b1=2) #不懂

tensor([[[ 1],
         [ 2],
         [13],
         [14],
         [ 5],
         [ 6],
         [17],
         [18],
         [ 9],
         [10],
         [21],
         [22]],

        [[ 3],
         [ 4],
         [15],
         [16],
         [ 7],
         [ 8],
         [19],
         [20],
         [11],
         [12],
         [23],
         [24]]])